version: '3'
services:
    web-api:
        image: nginx
        volumes:
        - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.template"
        - "./:/var/www/html"
        ports:
        - "9882:80"
        environment:
        - NGINX_HOST=${NGINX_HOST_API}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
        - php-api
    php-api:
        image: php:7.2-fpm
        restart: always
        depends_on:
            - composer
        volumes:
            - "./:/var/www/html"
    composer:
        image: composer:1.6
        working_dir: /app
        volumes:
            - "./:/app"
        command: "update -v --no-dev && install --no-dev --prefer-dist"
    mongo:
        image: mongo:4.1.5-xenial
        container_name: ${MONGO_HOST}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}